[mypy]
python_version = 3.14
files = parce
warn_redundant_casts = True
warn_unused_ignores = True

# Modules are locked down one at a time, as they get annotated.
[mypy-parce.tree]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lexer]
disallow_untyped_defs = True
disallow_incomplete_defs = True