[mypy]
python_version = 3.14
files = parce
warn_redundant_casts = True
warn_unused_ignores = True
enable_error_code = ignore-without-code, possibly-undefined

# Modules are locked down one at a time, as they get annotated.
[mypy-parce.tree]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lexer]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.treebuilderutil]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.treebuilder]
disallow_untyped_defs = True
disallow_incomplete_defs = True
disable_error_code = possibly-undefined

[mypy-parce.mutablestring]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.document]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.work]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.transform]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.util]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.ruleitem]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.query]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.css]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lang.css]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lang.lilypond]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lexicon]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.rule]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lang.numbers]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.unicharclass]
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-parce.lang.lilypond_words]
disallow_untyped_defs = True
disallow_incomplete_defs = True

